baseURL = "https://padonma.net/"
languageCode = "en-us"
title = "Padonma"
theme = "cardhaus"
assetDir = "assets"

enableRobotsTXT = true

[params]
  subtitle = "Burmese lotus fiber workshop"
  networkSubtitle = "Bootstrapping a global supply network for lotus fiber"
  description = "Padonma Network"
  author = "Padonma Network"
  logo = "brand/padonma_wordmark_and_rmqr.png"
  billboardImage = "temp/thailand-lotus-lake.jpg" 
  billboardLogo = "temp/padonma_logo.png"
  billboardTitle = ["Atelier", "Padonma"]
  topicsHeading = "Introduction"
  footerImage = "fluff/women_in_hat_and_thanaka.jpg"

  [params.cardhaus]
    customStylesheet = "css/padonma.css"

[menus]
  [[menus.main]]
    name = "HOME"
    pageRef = "/"
    weight = 1
  [[menus.main]]
    name = "TOPICS"
    pageRef = "/topics"
    weight = 2
  [[menus.main]]
    name = "BLOG"
    pageRef = "/posts"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
